### ISSUE TITLE
Unicode decoding error on Windows

### ISSUE THREAD

**Issue by benjaminestes** [benjaminestes/pyscape-client#10]
```
Traceback (most recent call last):
  File "pyscape", line 210, in <module>
    sys.exit(main())
  File "pyscape", line 205, in main
    do_csv(args, preset, data)
  File "pyscape", line 177, in do_csv
    writer.writerows(output)
  File "C:\Python33\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 141-148:
 character maps to <undefined>
```

**Comment by AbdullaRifai** [comment]
`class IncrementalEncoder(codecs.IncrementalEncoder):`
    `     def encode(self, input, final=False):`
        `     return codecs.charmap_encode(input,self.errors,encoding_table)[0]`

This is the source of my error, I am a novice at programming so didn't quite understand how the article solves the issue. Any input would be appreciated as to how you solved the problem, thanks in advance. (Or anyone, as this post is from 2013 so not sure if you remember this particular code)
