### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by jaceiverson** [benjaminestes/pyscape-client#31]
Hello Ben, 

I really appreciate you writing this wrapper for the MOZ API. I notice that this is for the version1 of the API, and since they have a version2. I attempted to make this work by changing the url string when you initialize the class, but this did not work. Do you have plans to updating this for v2?

**Comment by benjaminestes** [comment]
Hello @jaceiverson !

I don't make regular use of the Moz API anymore, and therefore I am unlikely to create a version of this library for v2 of their API. Apologies!
